version: '3'

networks:
  app:
    driver: bridge

services:
  app:
    image: node:16
    restart: unless-stopped
    user: node
    working_dir: /home/node/app
    volumes:
      - .:/home/node/app
    ports:
      - ${APP_PORT}:${APP_PORT}
    depends_on:
      - db
    entrypoint: ./.docker/entrypoint.sh
    networks:
      - app

  db:
    image: mysql:5.7
    restart: unless-stopped
    volumes:
      - ./.docker/db-data:/var/lib/mysql
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_RANDOM_ROOT_PASSWORD=true
    networks:
      - app